# Config package — centralised settings, paths, and branding
from broast_pos.config.config import (
    # General Settings
    APP_VERSION,
    DEBUG,
    ENVIRONMENT,
    LANGUAGE,
    # Business Rules
    AUTO_PRINT_KITCHEN,
    AUTO_PRINT_RECEIPT,
    DEFAULT_TAX_RATE,
    DISCOUNT_TYPES,
    MAX_DISCOUNT_PERCENT,
    ORDER_NUMBER_PREFIX,
    SERVICE_CHARGE_PCT,
    TABLE_COUNT,
    TAKEAWAY_AUTO_COMPLETE_MINUTES,
    TRACKING_REFRESH_SECONDS,
    # Paths
    BRANDING_PATH,
    DATABASE_PATH,
    FONTS_PATH,
    LOGS_PATH,
    PRINTER_CONFIG_PATH,
    RESTAURANT_CONFIG_PATH,
    # Restaurant loader
    get_app_name,
    get_category_colors,
    get_fonts,
    get_restaurant_info,
    get_theme,
    load_restaurant_config,
)

__all__ = [
    "APP_VERSION",
    "AUTO_PRINT_KITCHEN",
    "AUTO_PRINT_RECEIPT",
    "BRANDING_PATH",
    "DATABASE_PATH",
    "DEBUG",
    "DEFAULT_TAX_RATE",
    "DISCOUNT_TYPES",
    "ENVIRONMENT",
    "FONTS_PATH",
    "LANGUAGE",
    "LOGS_PATH",
    "MAX_DISCOUNT_PERCENT",
    "ORDER_NUMBER_PREFIX",
    "PRINTER_CONFIG_PATH",
    "RESTAURANT_CONFIG_PATH",
    "SERVICE_CHARGE_PCT",
    "TABLE_COUNT",
    "TAKEAWAY_AUTO_COMPLETE_MINUTES",
    "TRACKING_REFRESH_SECONDS",
    "get_app_name",
    "get_category_colors",
    "get_fonts",
    "get_restaurant_info",
    "get_theme",
    "load_restaurant_config",
]
